name: Scheduled BDD Tests

on:
  schedule:
    # Run tests every day at 6 AM UTC
    - cron: '0 6 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  scheduled-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
        
    - name: Setup ChromeDriver
      uses: nanasess/setup-chromedriver@v2
      
    - name: Run BDD Tests
      run: npm run wdio
      env:
        CI: true
        
    - name: Install Allure CLI
      if: always()
      run: |
        sudo apt-get update
        sudo apt-get install -y default-jre
        curl -o allure-2.24.0.tgz -L https://github.com/allure-framework/allure2/releases/download/2.24.0/allure-2.24.0.tgz
        tar -zxf allure-2.24.0.tgz
        sudo mv allure-2.24.0 /opt/allure
        sudo ln -s /opt/allure/bin/allure /usr/bin/allure
        
    - name: Generate Allure Report
      if: always()
      run: |
        allure generate allure-results --clean --output allure-report
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: scheduled-test-results
        path: |
          allure-results/
          allure-report/
          screenshots/
        retention-days: 7
        
    - name: Create Issue on Failure
      if: failure()
      uses: actions/github-script@v6
      with:
        script: |
          github.rest.issues.create({
            owner: context.repo.owner,
            repo: context.repo.repo,
            title: 'Scheduled Test Failure - ' + new Date().toISOString().split('T')[0],
            body: `## Scheduled Test Failure
            
            The scheduled BDD tests failed on ${new Date().toISOString()}.
            
            **Workflow Run:** ${context.payload.repository.html_url}/actions/runs/${context.runId}
            
            Please check the test results and fix any issues.
            
            **Auto-generated by GitHub Actions**`,
            labels: ['bug', 'test-failure', 'automated']
          })
